"""Update columns

Revision ID: 16fc99d8c905
Revises: 9582bf45a837
Create Date: 2023-10-30 22:07:33.682514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fc99d8c905'
down_revision = '9582bf45a837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs_table', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('blogs_table', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('blogs_table', sa.Column('published_on', sa.DateTime(), nullable=True))
    op.add_column('blogs_table', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('blogs_table', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs_table', 'category')
    op.drop_column('blogs_table', 'image_url')
    op.drop_column('blogs_table', 'published_on')
    op.drop_column('blogs_table', 'updated_at')
    op.drop_column('blogs_table', 'created_at')
    # ### end Alembic commands ###
